# Generated by Django 5.1.7 on 2025-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la categoria')),
                ('nombreCat', models.CharField(max_length=30, verbose_name='Nombre de la categoria')),
            ],
            options={
                'db_table': 'INICIO_CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de comuna')),
                ('nombreCom', models.CharField(max_length=40, verbose_name='Nombre comuna')),
            ],
            options={
                'db_table': 'INICIO_COMUNA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del detalle')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('subTotal', models.IntegerField(verbose_name='Subtotal')),
            ],
            options={
                'db_table': 'INICIO_DETALLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(db_column='IDDIRECCION', primary_key=True, serialize=False, verbose_name='Id de direccion')),
                ('descripcionDir', models.TextField(verbose_name='Descripcion direccion')),
            ],
            options={
                'db_table': 'INICIO_DIRECCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la marca')),
                ('nombreMarca', models.CharField(max_length=30, verbose_name='Nombre de la marca')),
            ],
            options={
                'db_table': 'INICIO_MARCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del modelo')),
                ('nombreModelo', models.CharField(max_length=30, verbose_name='Nombre del modelo')),
            ],
            options={
                'db_table': 'INICIO_MODELO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
                ('especificacionProd', models.CharField(max_length=900, verbose_name='Especificaciones del Producto')),
                ('stockProd', models.IntegerField(verbose_name='Stock del Producto')),
                ('imagenProd', models.ImageField(null=True, upload_to='productos', verbose_name='Imagen del Producto')),
            ],
            options={
                'db_table': 'INICIO_PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de region')),
                ('nombreReg', models.CharField(max_length=40, verbose_name='Nombre region')),
            ],
            options={
                'db_table': 'INICIO_REGION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('idTiporod', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del tipo producto')),
                ('nombreTipoProd', models.CharField(max_length=60, verbose_name='Nombre del tipo producto')),
            ],
            options={
                'db_table': 'INICIO_TIPOPROD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de venta')),
                ('fechaVenta', models.DateField(verbose_name='Fecha de venta')),
            ],
            options={
                'db_table': 'INICIO_VENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'INICIO_TIPOUSUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('tipousuario', models.ForeignKey(db_column='tipousuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Inicio.tipousuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'INICIO_USUARIO',
                'managed': True,
            },
        ),
    ]
