# Generated by Django 5.1.7 on 2025-05-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalle',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoprod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False},
        ),
    ]
